var wordBank = {
	positionArticles: [
		{word: "The"}
	],
	positionAdjectives: [
		{word: "Beloved"},
		{word: "Blessed"},
		{word: "Bold"},
		{word: "Chosen"},
		{word: "Courageous"},
		{word: "Cunning"},
		{word: "Everlasting"},
		{word: "Forsaken"},
		{word: "Glorious"},
		{word: "Grand"},
		{word: "High"},
		{word: "Holy"},
		{word: "Honored"},
		{word: "Immortal"},
		{word: "Imperial"},
		{word: "Magnificent"},
		{word: "Mighty"},
		{word: "Noble"},
		{word: "Once and Future"},
		{word: "One and only"},
		{word: "Righteous"}, 
		{word: "Royal"},
		{word: "Shining"},
		{word: "Sovereign"},
		{word: "Stalwart"},
		{word: "Undefeated"},
		{word: "Valiant"},
		{word: "Wise"},
		{word: "Mad"}
	],
	positionNouns: [
		{word: "Assassin", 		gender:""},
		{word: "Baron", 		gender:""},
		{word: "Baroness", 		gender:""},
		{word: "Bearer", 		gender:""},
		{word: "Caretaker", 	gender:""},
		{word: "Chancellor", 	gender:""},
		{word: "Chief", 		gender:""},
		{word: "Conqueror", 	gender:""},
		{word: "Defender", 		gender:""},
		{word: "Deliverer", 	gender:""},
		{word: "Destroyer", 	gender:""},
		{word: "Duchess", 		gender:""},
		{word: "Duke", 			gender:""},
		{word: "Emperor", 		gender:""},
		{word: "Empress", 		gender:""},
		{word: "Gaurdian", 		gender:""},
		{word: "General", 		gender:""},
		{word: "Seeker", 		gender:""},
		{word: "Heir", 			gender:""},
		{word: "Invader", 		gender:""},
		{word: "Judge", 		gender:""},
		{word: "Keeper", 		gender:""},
		{word: "King", 			gender:""},
		{word: "Lord", 			gender:""},
		{word: "Master", 		gender:""},
		{word: "Monarch", 		gender:""},
		{word: "Patriarch", 	gender:""},
		{word: "Pendragon", 	gender:""},
		{word: "Priest", 		gender:""},
		{word: "Prince", 		gender:""},
		{word: "Prophet", 		gender:""},
		{word: "Protector", 	gender:""},
		{word: "Queen", 		gender:""},
		{word: "Revolutionary", gender:""},
		{word: "Ruler", 		gender:""},
		{word: "Ruler", 		gender:""},
		{word: "Senator", 		gender:""},
		{word: "Sentinel", 		gender:""},
		{word: "Slayer", 		gender:""},
		{word: "Sorcerer", 		gender:""},
		{word: "Tyrant", 		gender:""},
		{word: "Viceroy", 		gender:""},
		{word: "Warlord", 		gender:""},
		{word: "Warrior", 		gender:""},
		{word: "Watchman", 		gender:""},
		{word: "Wizard", 		gender:""},
		{word: "Adventurer", 	gender:""},
		{word: "Monk", 			gender:""},
		{word: "Warlock", 		gender:""}
	],
	positionDomainPrepositions: [
		{word: "of the" }
	],
	domainAdjectives: [
		{word: "Ancient", 		isPlural: null },
		{word: "Black", 		isPlural: null },
		{word: "Bleeding", 		isPlural: null },
		{word: "Burning", 		isPlural: null },
		{word: "Chosen", 		isPlural: null },
		{word: "Dark", 			isPlural: null },
		{word: "Draconian", 	isPlural: null },
		{word: "Dwarven", 		isPlural: null },
		{word: "Eight", 		isPlural: true },
		{word: "Elder", 		isPlural: null },
		{word: "Eleven", 		isPlural: true },
		{word: "Elven", 		isPlural: null },
		{word: "Everlasting", 	isPlural: null },
		{word: "Faithful", 		isPlural: null },
		{word: "First", 		isPlural: null },
		{word: "Five", 			isPlural: true },
		{word: "Forsaken", 		isPlural: null },
		{word: "Four", 			isPlural: true },
		{word: "Golden", 		isPlural: null },
		{word: "Green", 		isPlural: null },
		{word: "Hidden", 		isPlural: null },
		{word: "Last", 			isPlural: null },
		{word: "Nine", 			isPlural: true },
		{word: "One", 			isPlural: false },
		{word: "Only", 			isPlural: false },
		{word: "Red", 			isPlural: null },
		{word: "Savage", 		isPlural: null },
		{word: "Seven", 		isPlural: true },
		{word: "Six", 			isPlural: true },
		{word: "Suffering", 	isPlural: null },
		{word: "Ten", 			isPlural: true },
		{word: "Three", 		isPlural: true },
		{word: "True", 			isPlural: null },
		{word: "Twelve", 		isPlural: true },
		{word: "White", 		isPlural: null },
		{word: "Cursed", 		isPlural: null },
	],
	domainNouns: [
		{singular: "Army"		, plural: "Armies"},
		{singular: "Band"		, plural: "Bands"},
		{singular: "City"		, plural: "Cities"},
		{singular: "Crown"		, plural: "Crowns"},
		{singular: "Dragon"		, plural: "Dragons"},
		{singular: "Dungeon"	, plural: "Dungeons"},
		{singular: "Dynasty"	, plural: "Dynasties"},
		{singular: "Field"		, plural: "Fields"},
		{singular: "Foe"		, plural: "Foes"},
		{singular: "Wood"		, plural: "Woods"},
		{singular: "Gate"		, plural: "Gates"},
		{singular: "Hall"		, plural: "Halls"},
		{singular: "Helm"		, plural: "Helms"},
		{singular: "House"		, plural: "Houses"},
		{singular: "Key"		, plural: "Keys"},
		{singular: "Kingdom"	, plural: "Kingdoms"},
		{singular: "Land"		, plural: "Lands"},
		{singular: "Legion"		, plural: "Legions"},
		{singular: "Nation"		, plural: "Nations"},
		{singular: "Orb"		, plural: "Orbs"},
		{singular: "Realm"		, plural: "Realms"},
		{singular: "Ring"		, plural: "Rings"},
		{singular: "Sage"		, plural: "Sages"},
		{singular: "Seal"		, plural: "Seals"},
		{singular: "Spear"		, plural: "Spears"},
		{singular: "Spire"		, plural: "Spires"},
		{singular: "Stone"		, plural: "Stones"},
		{singular: "Sword"		, plural: "Swords"},
		{singular: "Throne"		, plural: "Thrones"},
		{singular: "Tower"		, plural: "Towers"},
		{singular: "Tribe"		, plural: "Tribes"},
		{singular: "Wall"		, plural: "Walls"},
		{singular: "Warrior"	, plural: "Warriors"},
		{singular: "Wind"		, plural: "Winds"},
		{singular: "Scroll"		, plural: "Scrolls"},
		{singular: "Father"		, plural: "Fathers"},
		{singular: "Lord"		, plural: "Lords"},
		{singular: "Hill"		, plural: "Hills"},
		{singular: "Council"	, plural: "Councils"},
		{singular: "Spirit"		, plural: "Spirits"},
		{singular: "Mace"		, plural: "Maces"},
		{singular: "Hammer"		, plural: "Hammers"},
		{singular: "Fortress"	, plural: "Fortresses"},
		{singular: "Tome"		, plural: "Tomes"},
		{singular: "Gem"		, plural: "Gems"}
	],
	domainConceptPrepositions: [
		{word: "of"}
	],
	conceptNouns: [
		{word: "Battle"},
		{word: "Beauty"},
		{word: "Darkness"},
		{word: "Desire"},
		{word: "Desolation"},
		{word: "Destiny"},
		{word: "Doom"},
		{word: "Glory"},
		{word: "Hope"},
		{word: "Injustice"},
		{word: "Israel"},
		{word: "Justice"},
		{word: "Light"},
		{word: "Magic"},
		{word: "Mystery"},
		{word: "Peace"},
		{word: "Power"},
		{word: "the East"},
		{word: "the Moon"},
		{word: "the North"},
		{word: "the South"},
		{word: "the Sun"},
		{word: "the West"},
		{word: "Valiance"},
		{word: "Victory"},
		{word: "Virtue"},
		{word: "War"},
		{word: "Wealth"},
		{word: "the Sky"},
		{word: "Wrath"},
		{word: "the Sea"},
		{word: "Heaven"},
		{word: "Grace"},
		{word: "Rome"},
		{word: "the Forest"},
		{word: "the Plains"},
		{word: "the Seas"},
		{word: "the Gods"},
		{word: "Winter"},
		{word: "the Dead"}
	]
}